# https://docs.travis-ci.com/user/customizing-the-build/

sudo: false
language: node_js
node_js:
  - 8
  - 10
env:
  global:
    - PATH=$HOME/.yarn/bin:$PATH
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
matrix:
  fast_finish: true
script: yarn start ci
